Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/edgie/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/edgie/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 1031, in _main
    main()
  File "/home/edgie/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 673, in main
    esp = esp or get_default_connected_device(
  File "/home/edgie/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 920, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/home/edgie/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 640, in connect
    last_error = self._connect_attempt(reset_strategy, mode)
  File "/home/edgie/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 525, in _connect_attempt
    reset_strategy()  # Reset the chip to bootloader (download mode)
  File "/home/edgie/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esptool/reset.py", line 83, in __call__
    self._setDTRandRTS(False, False)
  File "/home/edgie/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esptool/reset.py", line 58, in _setDTRandRTS
    fcntl.ioctl(self.port.fileno(), TIOCMSET, struct.pack("I", status))
OSError: [Errno 71] Protocol error
CMake Error at run_serial_tool.cmake:63 (message):
  
  /home/edgie/.espressif/python_env/idf5.1_py3.10_env/bin/python;;/home/edgie/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s2
  failed.



